### ISSUE TITLE
You can try to create GitHub.io here

### ISSUE THREAD

**Issue by ljy-002** [Softencode/softencode.github.io#1]
no problem
You can try to create GitHub.io here: http://jekyllcn.com/

**Comment by ljy-002** [comment]
Maybe it can't be changed this time, but it can be next time
(Actually, you are fine now)

**Comment by MapMaths** [comment]
What problem?

**Comment by MapMaths** [comment]
Oh I understand. Actually I'd like to make an active webpage with script, but at last, thank you for advice~

**Comment by ljy-002** [comment]
you are welcome
