### ISSUE TITLE
This is not available

### ISSUE THREAD

**Issue by ljy-002** [Softencode/softencode.github.io#2]
This is not available:
https://github.com/Softencode/softencode.github.io/blob/master/projects/libraries/isd1820/index.md
You need to pull the request again

**Comment by ljy-002** [comment]
Or you can change it:
https://github.com/Softencode/softencode.github.io/blob/master/index.md
To:
https://softencode.github.io/projects/libraries/isd1820

**Comment by ljy-002** [comment]
I changed it for you. If you think it’s okay, then please agree to my changes

**Comment by ljy-002** [comment]
I asked the question because I wanted to develop the softencode.github.io library
——too
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This library is under development, I think I can make some suggestions

**Comment by MapMaths** [comment]
Thanks for developing, request pulled :)
